### ISSUE TITLE
Determine how to best handle missing PTF  SF99703 Level 11 - V7R3

### ISSUE THREAD

**Issue by richardschoen** [ThePrez/ServiceCommander-IBMi#3]
child process python3:Traceback (most recent call last):
child process python3:  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1254                    , in _prepare_helper
child process python3:    self.stmt_handler = ibm_db.prepare(self.conn_handler, operation)
child process python3:Exception: Named argument DETAILED_INFO for routine ACTIVE_JOB_INFO not vali                    d for reason code 1. SQLSTATE=4274K SQLCODE=-20483
child process python3:
child process python3:During handling of the above exception, another exception occurred:
child process python3:
child process python3:Traceback (most recent call last):
child process python3:  File "<stdin>", line 11, in <module>
child process python3:  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1394                    , in execute
child process python3:    self._prepare_helper(operation)
child process python3:  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1257                    , in _prepare_helper
child process python3:    raise self.messages[-1]
child process python3:ibm_db_dbi.ProgrammingError: ibm_db_dbi::ProgrammingError: Named argument DE                    TAILED_INFO for routine ACTIVE_JOB_INFO not valid for reason code 1. SQLSTATE=4274K SQLCODE=-20483
Unable to retrieve performance data for job 588565/POSTGRES/PGCTL (it may be no longer active)

**Comment by ThePrez** [comment]
As part of commit 537f366bebd87f41c71a2057bbb0f58eee3d4dee I put in the missing PTFs as a possible reason for failure. Not a complete or best solution, but it's a start. Keeping this issue open until something more comprehensive is done or we decided the beefed-up error and doc is enough.
