### ISSUE TITLE
[BUG] Cannot end jobs submitted with custom *JOBQ

### ISSUE THREAD

**Issue by ThePrez** [ThePrez/ServiceCommander-IBMi#34]
**Describe the bug**
When a job is configured with a custom job queue, for instance:
```
batch_mode: yes
sbmjob_jobname: Kafka
sbmjob_opts: "JOBQ(QSYS/QUSRNOMAX) USER(JGORZINS)"
```
The `sc stop` fails. This is because the stop command also specifies JOBQ on the SBMJOB command.

**To Reproduce**
See bug description

**Expected behavior**
User-specified JOBQ should be ignored on the `sc stop` flow

**Verbose output**
```
Verbose mode enabled
--------------------
Initializing service zookeeper
Loading yaml service definition from file /QOpenSys/etc/sc/services/zookeeper.yaml
Initializing service kafka
Loading yaml service definition from file /QOpenSys/etc/sc/services/kafka.yaml
Initializing service as-database
Loading yaml service definition from file /QOpenSys/etc/sc/services/as-database.yaml
Initializing service ftp
Loading yaml service definition from file /QOpenSys/etc/sc/services/ftp.yml
Initializing service as-central
Loading yaml service definition from file /QOpenSys/etc/sc/services/as-central.yaml
Initializing service navigator
Loading yaml service definition from file /QOpenSys/etc/sc/services/navigator.yaml
Initializing service kafkaviz
Loading yaml service definition from file /QOpenSys/etc/sc/services/kafkaviz.yaml
Initializing service gitbucket
Loading yaml service definition from file /QOpenSys/etc/sc/services/gitbucket.yaml
Looking for services in group 'default'
Services in group 'default' are: [kafka]
Performing operation 'STOP' on service 'kafka'
database says current time is 2021-03-23-04.03.10
Attempting to stop dependent service 'Apache Kafka Visualizer'...
database says current time is 2021-03-23-04.03.10
Service 'Apache Kafka Visualizer' is already stopped
using custom sbmJobOpts: JOBQ(QSYS/QUSRNOMAX) JOBQ(QUSRNOMAX) HOLD(*NO)
child process kafka:Command is > SBMJOB CMD(CALL PGM(QP2SHELL2) PARM('/QOpenSys/pkgs/bin/bash' '-c' 'cd /home/JGORZINS/mykafka/kafka_2.13-2.6.0/config && env && exec ../bin/kafka-server-stop.sh server.properties')) CPYENVVAR(*YES) PRTDEV(*USRPRF) ALWMLTTHD(*YES) JOB(binkafkase) JOBQ(QSYS/QUSRNOMAX) JOBQ(QUSRNOMAX) HOLD(*NO)  <
child process kafka:CPD0042: Parameter JOBQ specified more than once.
child process kafka:CPF0006: Errors occurred in command.
WARNING: Timed out waiting for service 'Apache Kafka bootstrap server' to stop. Will try harder
Ending job with: /QOpenSys/pkgs/bin/db2util -o space CALL QSYS2.QCMDEXC('SBMJOB JOBQ(QSYS/QUSRNOMAX) JOBQ(QUSRNOMAX) HOLD(*NO) CMD(ENDJOB JOB(963101/JGORZINS/KAFKA) OPTION(*IMMED))')
ERROR: Timed out waiting for service 'Apache Kafka bootstrap server' to stop. Giving up

java.lang.RuntimeException
        at jesseg.ibmi.opensource.SCException.<init>(SCException.java:26)
        at jesseg.ibmi.opensource.OperationExecutor.stopService(OperationExecutor.java:617)
        at jesseg.ibmi.opensource.OperationExecutor.execute(OperationExecutor.java:141)
        at jesseg.ibmi.opensource.ServiceCommander.performOperationsOnServices(ServiceCommander.java:208)
        at jesseg.ibmi.opensource.ServiceCommander.main(ServiceCommander.java:162)

jesseg.ibmi.opensource.SCException: ERROR: Timed out waiting for service 'Apache Kafka bootstrap server' to stop. Giving up

        at jesseg.ibmi.opensource.OperationExecutor.stopService(OperationExecutor.java:617)
        at jesseg.ibmi.opensource.OperationExecutor.execute(OperationExecutor.java:141)
        at jesseg.ibmi.opensource.ServiceCommander.performOperationsOnServices(ServiceCommander.java:208)
        at jesseg.ibmi.opensource.ServiceCommander.main(ServiceCommander.java:162)
Caused by: java.lang.RuntimeException
        at jesseg.ibmi.opensource.SCException.<init>(SCException.java:26)
        ... 4 more
```
**Additional context**

**Comment by ThePrez** [comment]
Resolved by #33
